// Compute leaderboard from GAMES (data.js) and render the page.

function computeStandings(games) {
  const players = new Map(); // name -> { name, played, correct, packs }

  games.forEach(game => {
    Object.entries(game.options).forEach(([option, voters]) => {
      const right = option === game.winner;
      voters.forEach(name => {
        if (!players.has(name)) {
          players.set(name, { name, played: 0, correct: 0, packs: 0 });
        }
        const p = players.get(name);
        p.played += 1;
        if (right) { p.correct += 1; p.packs += 1; }
      });
    });
  });

  const rows = [...players.values()].map(p => ({
    ...p,
    pct: p.played ? Math.round((p.correct / p.played) * 100) : 0
  }));

  // Sort: most correct, then accuracy, then fewest played, then name.
  rows.sort((a, b) =>
    b.correct - a.correct ||
    b.pct - a.pct ||
    a.played - b.played ||
    a.name.localeCompare(b.name)
  );

  // Dense rank with ties (same correct + pct share a rank).
  let rank = 0, prevKey = null;
  rows.forEach((r, i) => {
    const key = `${r.correct}|${r.pct}`;
    if (key !== prevKey) { rank = i + 1; prevKey = key; }
    r.rank = rank;
  });

  return rows;
}

function initials(name) {
  return name.split(/\s+/).slice(0, 2).map(w => w[0]).join("").toUpperCase();
}

// ---------- Pack pickups ----------
// Baseline (shared, committed) lives in pickups.js as COLLECTED: name -> count.
// Your local ticks live in localStorage so they're instant and don't need a
// deploy; "Copy pickup list" turns them into a new committed baseline.
const PICKUP_KEY = "bs-wc-pickups-v1";
const PICKUP_BASELINE = (typeof COLLECTED !== "undefined" && COLLECTED) || {};

function loadPickups() {
  try {
    const saved = JSON.parse(localStorage.getItem(PICKUP_KEY));
    if (saved && typeof saved === "object") return saved;
  } catch (e) { /* corrupt/empty — fall back to baseline */ }
  return { ...PICKUP_BASELINE };
}
let pickups = loadPickups();
const collectedCount = name => Math.max(0, pickups[name] || 0);

function togglePickup(el) {
  const name = el.dataset.player;
  const owed = Number(el.dataset.owed);
  pickups[name] = el.checked ? owed : 0;
  localStorage.setItem(PICKUP_KEY, JSON.stringify(pickups));
  render();
}

// How many ticks differ from the committed baseline (i.e. need a deploy).
function pickupsDirty() {
  const names = new Set([...Object.keys(PICKUP_BASELINE), ...Object.keys(pickups)]);
  let n = 0;
  names.forEach(name => { if ((PICKUP_BASELINE[name] || 0) !== (pickups[name] || 0)) n++; });
  return n;
}

// Build the exact pickups.js contents from the current ticks.
function pickupsFileText() {
  const entries = Object.entries(pickups)
    .filter(([, c]) => c > 0)
    .sort((a, b) => a[0].localeCompare(b[0]));
  const body = entries.map(([n, c]) => `  ${JSON.stringify(n)}: ${c}`).join(",\n");
  return "// Pack pickups (committed baseline). name -> packs collected.\n" +
    "// Generated by the leaderboard's \"Copy pickup list\" button — paste & deploy.\n" +
    "const COLLECTED = {\n" + (body ? body + "\n" : "") + "};\n";
}

function copyPickups() {
  const btn = document.querySelector(".pickups-save");
  navigator.clipboard.writeText(pickupsFileText()).then(() => {
    if (btn) { btn.textContent = "Copied — paste into pickups.js & deploy"; btn.classList.add("done"); }
  }).catch(() => {
    if (btn) btn.textContent = "Copy failed — check clipboard permissions";
  });
}

function renderPickupsBar(rows) {
  const pending = rows.reduce((s, r) => s + Math.max(0, r.packs - collectedCount(r.name)), 0);
  const people = rows.filter(r => r.packs - collectedCount(r.name) > 0).length;
  const dirty = pickupsDirty();
  document.getElementById("pickups-bar").innerHTML = `
    <span class="pickups-summary">🎁 ${pending} pack${pending === 1 ? "" : "s"} awaiting pickup${people ? ` · ${people} ${people === 1 ? "person" : "people"}` : ""}</span>
    <div class="pickups-actions">
      ${dirty
        ? `<span class="pickups-dirty">${dirty} unsaved change${dirty === 1 ? "" : "s"}</span>
           <button class="pickups-save" onclick="copyPickups()">Copy pickup list to commit</button>`
        : `<span class="pickups-clean">All pickups saved ✓</span>`}
    </div>`;
}

function render() {
  const rows = computeStandings(GAMES);

  // Totals
  const totalPacks = rows.reduce((s, r) => s + r.packs, 0);
  const totalCorrect = rows.reduce((s, r) => s + r.correct, 0);
  const totalGuesses = rows.reduce((s, r) => s + r.played, 0);
  const perfect = rows.filter(r => r.played === GAMES.length && r.pct === 100).length;

  document.getElementById("stat-players").textContent = rows.length;
  document.getElementById("stat-games").textContent = GAMES.length;
  document.getElementById("stat-packs").textContent = totalPacks;
  document.getElementById("stat-accuracy").textContent =
    Math.round((totalCorrect / totalGuesses) * 100) + "%";

  // Leaderboard
  const tbody = document.getElementById("leaderboard-body");
  tbody.innerHTML = rows.map(r => {
    const medal = r.rank === 1 ? "gold" : r.rank === 2 ? "silver" : r.rank === 3 ? "bronze" : "";
    const isPerfect = r.played === GAMES.length && r.pct === 100;
    const got = Math.min(collectedCount(r.name), r.packs);
    const caughtUp = r.packs > 0 && got >= r.packs;
    const collectedCell = r.packs === 0
      ? '<span class="pickup-status muted">—</span>'
      : `<label class="pickup">
           <input type="checkbox" data-player="${r.name}" data-owed="${r.packs}"
                  ${caughtUp ? "checked" : ""} onchange="togglePickup(this)" />
           <span class="pickup-status">${caughtUp ? "✓" : `${got}/${r.packs}`}</span>
         </label>`;
    return `
      <tr class="${medal ? "podium " + medal : ""}${caughtUp ? " collected-done" : ""}">
        <td class="col-rank"><span class="rank-badge">${r.rank}</span></td>
        <td class="col-player">
          <span class="avatar">${initials(r.name)}</span>
          <span class="player-name">${r.name}${isPerfect ? ' <span class="perfect-tag">PERFECT</span>' : ""}</span>
        </td>
        <td class="col-num">${r.played}</td>
        <td class="col-num strong">${r.correct}</td>
        <td class="col-num">
          <div class="pct-wrap">
            <div class="pct-bar"><span style="width:${r.pct}%"></span></div>
            <span class="pct-label">${r.pct}%</span>
          </div>
        </td>
        <td class="col-packs">${r.packs > 0 ? "🎁".repeat(r.packs) + ` <b>${r.packs}</b>` : "—"}</td>
        <td class="col-collected">${collectedCell}</td>
      </tr>
    `;
  }).join("");

  renderPickupsBar(rows);
}

render();
