// Pack pickups (committed baseline). name -> packs collected.
// Generated by the leaderboard's "Copy pickup list" button — paste & deploy.
const COLLECTED = {
  "Amaya Rutherford": 3,
  "Ariel": 5,
  "becky": 5,
  "Camila": 4,
  "Carlo Shyrbi": 1,
  "Cris": 6,
  "Ello Han": 5,
  "Fatima Mohomud": 3,
  "George Thomas": 7,
  "Gui": 2,
  "Haimini": 5,
  "Hash": 1,
  "Madeleine McCartney": 6,
  "Mariana": 6,
  "Mauricio": 5,
  "Merve": 3,
  "Paola Han": 4,
  "Patricia Palasz": 6,
  "Rafael": 6,
  "Rory": 5,
  "Sophie Hills": 4,
  "Yasmin": 5
};
